name: onycha
description: A router for RawDart SPA Development and AngularDart Development.
version: 1.0.16-dev.1
homepage: https://github.com/arxarinze/swipy

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  angular: ^6.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
